---
title: "cine argentina"
author: "Maximiliano Ros"
date: "12/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#library(pdftools)
#library(tabulizer)
#library(tabulizerjars)
library(readxl)
library(scales)
library(showtext)
font_add(family="BRLNSR" ,regular="BRLNSR.TTF")
showtext_auto()
library(ggtext)
```

#SEMANAS DEL 2021 
```{r}
#SEMANA 36
semana.36<- read.csv2("semana36-03.09.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.36<- semana.36 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "03-09-2021", semana=36)

#SEMANA 37
semana.37<- read.csv2("semana37-10.09.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.37<- semana.37  %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "10-09-2021", semana=37)

#SEMANA 38
semana.38<- read.csv2("semana38-16.09.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.38<-semana.38 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "16-09-2021", semana=38)

#SEMANA 39
semana.39<- read.csv2("semana39-23.09.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.39<- semana.39 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "23-09-2021",semana=39)
  
#SEMANA 40  
semana.40<- read.csv2("semana40-30.09.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.40<- semana.40 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "30-09-2021", semana=40)

#SEMANA 41
semana.41<- read.csv2("semana41-07.10.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.41<- semana.41 %>%  summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "07-10-2021", semana=41)

#SEMANA 42
semana.42<- read.csv2("semana42-14.10.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.42<- semana.42 %>%  summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "14-10-2021", semana=42)

#SEMANA 43
semana.43<- read.csv2("semana43-21.10.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.43<- semana.43 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "21-10-2021", semana=43)

#SEMANA 44
semana.44<- read.csv2("semana44-28.10.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.44<-semana.44 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha="28-10-2021", semana=44)


#SEMANA 45
semana.45<- read.csv2("semana45-04.11.csv") %>% select(-entradas_total..v_is_pelicula_diario.)
semana.45<- semana.45 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha="04-11-2021", semana=45)

#SEMANA 46
semana.46<- read.csv2("semana46-11.11.csv") 
semana.46<- semana.46 %>% summarise(estreno=ï..Fecha.Estreno, titulo=ing.Titulo, espectadores.semanales=Espec..Semana, semanas.en.cartelera= Semana.Cartel, pantallas.proyectadas=Pantallas, fecha= "11-11-2021", semana=46)

#SEMANA 47 
semana.47<- read.csv2("semana47-18.11.csv")

semanas<- bind_rows(semana.36,semana.37,semana.38,semana.39,semana.40,semana.41,semana.42,semana.43,semana.44,semana.45,semana.46) 
semanas$fecha<- as.Date(semanas$fecha, "%d-%m-%Y")
```



```{r}
#Estrenos semana 47
estrenos.47<- semana.47 %>% filter(Semana.Cartel==1)

estrenos.47$ing.Titulo[grepl("LA CRONICA", estrenos.47$ing.Titulo)]<- "THE FRENCH \nDISPATCH"
estrenos.47$ing.Titulo[grepl("EL MISTERIO DE SOHO", estrenos.47$ing.Titulo)]<-"LAST NIGHT \nIN SOHO"
estrenos.47$ing.Titulo[grepl("RIESGO", estrenos.47$ing.Titulo)]<-"THE ICE ROAD"
estrenos.47$ing.Titulo[grepl("LA CASA DE GUCCI", estrenos.47$ing.Titulo)]<-"HOUSE OF \nGUCCI"
estrenos.47$ing.Titulo[grepl("RETIROS", estrenos.47$ing.Titulo)]<-"RETIROS \n(IN)VOLUNTARIOS"
```

```{r}
grafico.ig<-estrenos.47 %>% filter(ing.Titulo!= "SUPER JUNIOR WORLD TOUR [SUPER SHOW 8 : INFINITE TIME]" & Espec..Semana>257) %>% mutate(ing.Titulo= fct_reorder(ing.Titulo, Espec..Semana))

ggplot(grafico.ig,aes(x=Espec..Semana, y=ing.Titulo, label=Espec..Semana))+
  geom_bar(stat="identity", fill="#FA8806")+
  annotate("text",x=1200, y= "RETIROS \n(IN)VOLUNTARIOS", label="258",family="BRLNSR" )+
  annotate("text",x=2000, y= "ONE PIECE GOLD", label="886",family="BRLNSR" )+
  annotate("text",x=9500, y= "THE ICE ROAD", label="11381",family="BRLNSR" )+
  annotate("text",x=13500, y= "LAST NIGHT \nIN SOHO", label="15683",family="BRLNSR" )+
  annotate("text",x=14500, y= "THE FRENCH \nDISPATCH", label="16508",family="BRLNSR" )+
  scale_x_continuous()+
  labs(x="", title="Cine en <span style='color: #FA8806;'>**Argentina**</span>", subtitle = "Los 5 mejores estrenos <br>por espectadores de la semana")+
  theme(plot.title.position = "plot",
        plot.title = element_markdown(family="BRLNSR", size=24),
        plot.subtitle = element_markdown(family="BRLNSR", size=14), 
        panel.background = element_blank(),axis.ticks = element_blank(),
        plot.caption = element_markdown(size=8,hjust=0,family = "BRLNSR" ), 
        text = element_text(family = ""),
        panel.grid.major = element_blank(),
        legend.position = "none",
        legend.box.background =  element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), 
        axis.text = element_markdown(size=9.5,family = "BRLNSR", colour = "BLACK"), 
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        aspect.ratio = 16/10)

ggsave("cine.argentina.png", height = )
```






